- hosts: controller
  remote_user: heat-admin
  gather_facts: false
  vars:
    ansible_become: true
  roles:
  - legacy-controller

- hosts: compute
  remote_user: heat-admin
  gather_facts: false
  vars:
    ansible_become: true
  roles:
  - legacy-compute
