- name: configuring dvr
  ini_file:
    dest: /etc/neutron/neutron.conf
    mode: 0640
    section: DEFAULT
    option: router_distributed
    value: False
    backup: yes
  notify:
    - unmanage neutron services
    - restart neutron services
    - manage neutron services
    - cleanup neutron services
- name: configure  l3 agent
  ini_file:
    dest: /etc/neutron/l3_agent.ini
    mode: 0640
    section: DEFAULT
    option: agent_mode
    value: legacy
    backup: yes
  notify:
    - unmanage neutron services
    - restart neutron services
    - manage neutron services
    - cleanup neutron services
- name: configure l2 agent
  ini_file:
    dest: /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
    mode: 0640
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
   - { section: agent, option: enable_distributed_routing, value: False }
   - { section: agent, option: l2_population, value: False }
  notify:
    - unmanage neutron services
    - restart neutron services
    - manage neutron services
    - cleanup neutron services

- name: enable l2 population driver
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    mode: 0640
    section: ml2
    option: mechanism_drivers
    value: openvswitch, linuxbridge
  notify:
    - unmanage neutron services
    - restart neutron services
    - manage neutron services
    - cleanup neutron services
